# Generated by Django 4.0.6 on 2022-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_details',
            name='m_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill_transaction',
            name='bill_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill_transaction',
            name='farmer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chicken_batch_details',
            name='company_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chicken_batch_details',
            name='no_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='daily_batchlog',
            name='batch_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='daily_feedinglog',
            name='batch_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor_consultation',
            name='batch_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor_consultation',
            name='farmer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_batch_sales',
            name='company_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_batch_sales',
            name='farmer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_manager_query',
            name='farmer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_manager_query',
            name='manager_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='general_info',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='general_info',
            name='manager_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='general_info',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
