# Generated by Django 4.0.6 on 2022-07-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_manager_details_m_id_alter_bill_transaction_bill_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager_details',
            name='m_id',
        ),
    ]
