# Generated by Django 4.0.6 on 2022-07-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_manager_details_m_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
