# Generated by Django 4.0.6 on 2022-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='gender',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
