# Generated by Django 4.0.6 on 2022-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctor_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='dob',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
