# Generated by Django 4.0.6 on 2022-07-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_details_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='company_name',
            new_name='name',
        ),
    ]
