# Generated by Django 4.0.6 on 2022-07-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_company_name_company_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
