# Generated by Django 4.0.6 on 2022-07-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_company_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
