# Generated by Django 3.2.15 on 2022-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_supervisor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_details',
            name='company_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
