# Generated by Django 3.2.15 on 2022-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_manager_details_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor_details',
            name='manager_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
