# Generated by Django 3.2.15 on 2022-08-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_manager_id_supervisor_details_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_feedinglog',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
