# Generated by Django 3.2.15 on 2022-08-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_daily_feedinglog_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_consultation',
            name='time',
        ),
        migrations.AddField(
            model_name='doctor_consultation',
            name='tm',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
