# Generated by Django 3.2.15 on 2022-08-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20220810_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='company_id',
            field=models.IntegerField(),
        ),
    ]
