# Generated by Django 3.2.15 on 2022-08-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_doctor_details_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_consultation',
            name='doctor_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
