# Generated by Django 3.2.15 on 2022-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_farmer_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_farmer_sales',
            name='farmer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
