# Generated by Django 3.2.15 on 2022-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_shop_farmer_sales_farmer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_farmer_sales',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
